/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdStreamsRouteImport } from './routes/projects.$projectId.streams'
import { Route as ProjectsProjectIdSettingsRouteImport } from './routes/projects.$projectId.settings'
import { Route as ProjectsProjectIdPublishRouteImport } from './routes/projects.$projectId.publish'
import { Route as ProjectsProjectIdEstuariesRouteImport } from './routes/projects.$projectId.estuaries'
import { Route as ProjectsProjectIdStreamsIndexRouteImport } from './routes/projects.$projectId.streams.index'
import { Route as ProjectsProjectIdEstuariesIndexRouteImport } from './routes/projects.$projectId.estuaries.index'
import { Route as ProjectsProjectIdStreamsStreamIdRouteImport } from './routes/projects.$projectId.streams.$streamId'
import { Route as ProjectsProjectIdEstuariesIdRouteImport } from './routes/projects.$projectId.estuaries.$id'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdStreamsRoute =
  ProjectsProjectIdStreamsRouteImport.update({
    id: '/streams',
    path: '/streams',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSettingsRoute =
  ProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPublishRoute =
  ProjectsProjectIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdEstuariesRoute =
  ProjectsProjectIdEstuariesRouteImport.update({
    id: '/estuaries',
    path: '/estuaries',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdStreamsIndexRoute =
  ProjectsProjectIdStreamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdStreamsRoute,
  } as any)
const ProjectsProjectIdEstuariesIndexRoute =
  ProjectsProjectIdEstuariesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectIdEstuariesRoute,
  } as any)
const ProjectsProjectIdStreamsStreamIdRoute =
  ProjectsProjectIdStreamsStreamIdRouteImport.update({
    id: '/$streamId',
    path: '/$streamId',
    getParentRoute: () => ProjectsProjectIdStreamsRoute,
  } as any)
const ProjectsProjectIdEstuariesIdRoute =
  ProjectsProjectIdEstuariesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProjectsProjectIdEstuariesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/estuaries': typeof ProjectsProjectIdEstuariesRouteWithChildren
  '/projects/$projectId/publish': typeof ProjectsProjectIdPublishRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/streams': typeof ProjectsProjectIdStreamsRouteWithChildren
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/estuaries/$id': typeof ProjectsProjectIdEstuariesIdRoute
  '/projects/$projectId/streams/$streamId': typeof ProjectsProjectIdStreamsStreamIdRoute
  '/projects/$projectId/estuaries/': typeof ProjectsProjectIdEstuariesIndexRoute
  '/projects/$projectId/streams/': typeof ProjectsProjectIdStreamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectId/publish': typeof ProjectsProjectIdPublishRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/estuaries/$id': typeof ProjectsProjectIdEstuariesIdRoute
  '/projects/$projectId/streams/$streamId': typeof ProjectsProjectIdStreamsStreamIdRoute
  '/projects/$projectId/estuaries': typeof ProjectsProjectIdEstuariesIndexRoute
  '/projects/$projectId/streams': typeof ProjectsProjectIdStreamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectId/estuaries': typeof ProjectsProjectIdEstuariesRouteWithChildren
  '/projects/$projectId/publish': typeof ProjectsProjectIdPublishRoute
  '/projects/$projectId/settings': typeof ProjectsProjectIdSettingsRoute
  '/projects/$projectId/streams': typeof ProjectsProjectIdStreamsRouteWithChildren
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/estuaries/$id': typeof ProjectsProjectIdEstuariesIdRoute
  '/projects/$projectId/streams/$streamId': typeof ProjectsProjectIdStreamsStreamIdRoute
  '/projects/$projectId/estuaries/': typeof ProjectsProjectIdEstuariesIndexRoute
  '/projects/$projectId/streams/': typeof ProjectsProjectIdStreamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/estuaries'
    | '/projects/$projectId/publish'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/streams'
    | '/projects/$projectId/'
    | '/projects/$projectId/estuaries/$id'
    | '/projects/$projectId/streams/$streamId'
    | '/projects/$projectId/estuaries/'
    | '/projects/$projectId/streams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectId/publish'
    | '/projects/$projectId/settings'
    | '/projects/$projectId'
    | '/projects/$projectId/estuaries/$id'
    | '/projects/$projectId/streams/$streamId'
    | '/projects/$projectId/estuaries'
    | '/projects/$projectId/streams'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/'
    | '/projects/$projectId/estuaries'
    | '/projects/$projectId/publish'
    | '/projects/$projectId/settings'
    | '/projects/$projectId/streams'
    | '/projects/$projectId/'
    | '/projects/$projectId/estuaries/$id'
    | '/projects/$projectId/streams/$streamId'
    | '/projects/$projectId/estuaries/'
    | '/projects/$projectId/streams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/streams': {
      id: '/projects/$projectId/streams'
      path: '/streams'
      fullPath: '/projects/$projectId/streams'
      preLoaderRoute: typeof ProjectsProjectIdStreamsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/settings': {
      id: '/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof ProjectsProjectIdSettingsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/publish': {
      id: '/projects/$projectId/publish'
      path: '/publish'
      fullPath: '/projects/$projectId/publish'
      preLoaderRoute: typeof ProjectsProjectIdPublishRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/estuaries': {
      id: '/projects/$projectId/estuaries'
      path: '/estuaries'
      fullPath: '/projects/$projectId/estuaries'
      preLoaderRoute: typeof ProjectsProjectIdEstuariesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/streams/': {
      id: '/projects/$projectId/streams/'
      path: '/'
      fullPath: '/projects/$projectId/streams/'
      preLoaderRoute: typeof ProjectsProjectIdStreamsIndexRouteImport
      parentRoute: typeof ProjectsProjectIdStreamsRoute
    }
    '/projects/$projectId/estuaries/': {
      id: '/projects/$projectId/estuaries/'
      path: '/'
      fullPath: '/projects/$projectId/estuaries/'
      preLoaderRoute: typeof ProjectsProjectIdEstuariesIndexRouteImport
      parentRoute: typeof ProjectsProjectIdEstuariesRoute
    }
    '/projects/$projectId/streams/$streamId': {
      id: '/projects/$projectId/streams/$streamId'
      path: '/$streamId'
      fullPath: '/projects/$projectId/streams/$streamId'
      preLoaderRoute: typeof ProjectsProjectIdStreamsStreamIdRouteImport
      parentRoute: typeof ProjectsProjectIdStreamsRoute
    }
    '/projects/$projectId/estuaries/$id': {
      id: '/projects/$projectId/estuaries/$id'
      path: '/$id'
      fullPath: '/projects/$projectId/estuaries/$id'
      preLoaderRoute: typeof ProjectsProjectIdEstuariesIdRouteImport
      parentRoute: typeof ProjectsProjectIdEstuariesRoute
    }
  }
}

interface ProjectsProjectIdEstuariesRouteChildren {
  ProjectsProjectIdEstuariesIdRoute: typeof ProjectsProjectIdEstuariesIdRoute
  ProjectsProjectIdEstuariesIndexRoute: typeof ProjectsProjectIdEstuariesIndexRoute
}

const ProjectsProjectIdEstuariesRouteChildren: ProjectsProjectIdEstuariesRouteChildren =
  {
    ProjectsProjectIdEstuariesIdRoute: ProjectsProjectIdEstuariesIdRoute,
    ProjectsProjectIdEstuariesIndexRoute: ProjectsProjectIdEstuariesIndexRoute,
  }

const ProjectsProjectIdEstuariesRouteWithChildren =
  ProjectsProjectIdEstuariesRoute._addFileChildren(
    ProjectsProjectIdEstuariesRouteChildren,
  )

interface ProjectsProjectIdStreamsRouteChildren {
  ProjectsProjectIdStreamsStreamIdRoute: typeof ProjectsProjectIdStreamsStreamIdRoute
  ProjectsProjectIdStreamsIndexRoute: typeof ProjectsProjectIdStreamsIndexRoute
}

const ProjectsProjectIdStreamsRouteChildren: ProjectsProjectIdStreamsRouteChildren =
  {
    ProjectsProjectIdStreamsStreamIdRoute:
      ProjectsProjectIdStreamsStreamIdRoute,
    ProjectsProjectIdStreamsIndexRoute: ProjectsProjectIdStreamsIndexRoute,
  }

const ProjectsProjectIdStreamsRouteWithChildren =
  ProjectsProjectIdStreamsRoute._addFileChildren(
    ProjectsProjectIdStreamsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdEstuariesRoute: typeof ProjectsProjectIdEstuariesRouteWithChildren
  ProjectsProjectIdPublishRoute: typeof ProjectsProjectIdPublishRoute
  ProjectsProjectIdSettingsRoute: typeof ProjectsProjectIdSettingsRoute
  ProjectsProjectIdStreamsRoute: typeof ProjectsProjectIdStreamsRouteWithChildren
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdEstuariesRoute: ProjectsProjectIdEstuariesRouteWithChildren,
  ProjectsProjectIdPublishRoute: ProjectsProjectIdPublishRoute,
  ProjectsProjectIdSettingsRoute: ProjectsProjectIdSettingsRoute,
  ProjectsProjectIdStreamsRoute: ProjectsProjectIdStreamsRouteWithChildren,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
