/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamsRouteImport } from './routes/streams'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StreamsStreamIdRouteImport } from './routes/streams.$streamId'
import { Route as ApiSseIdRouteImport } from './routes/api/sse.$id'

const StreamsRoute = StreamsRouteImport.update({
  id: '/streams',
  path: '/streams',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StreamsStreamIdRoute = StreamsStreamIdRouteImport.update({
  id: '/$streamId',
  path: '/$streamId',
  getParentRoute: () => StreamsRoute,
} as any)
const ApiSseIdRoute = ApiSseIdRouteImport.update({
  id: '/api/sse/$id',
  path: '/api/sse/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/streams': typeof StreamsRouteWithChildren
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/api/sse/$id': typeof ApiSseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/streams': typeof StreamsRouteWithChildren
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/api/sse/$id': typeof ApiSseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/streams': typeof StreamsRouteWithChildren
  '/streams/$streamId': typeof StreamsStreamIdRoute
  '/api/sse/$id': typeof ApiSseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/streams' | '/streams/$streamId' | '/api/sse/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/streams' | '/streams/$streamId' | '/api/sse/$id'
  id: '__root__' | '/' | '/streams' | '/streams/$streamId' | '/api/sse/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StreamsRoute: typeof StreamsRouteWithChildren
  ApiSseIdRoute: typeof ApiSseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/streams': {
      id: '/streams'
      path: '/streams'
      fullPath: '/streams'
      preLoaderRoute: typeof StreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streams/$streamId': {
      id: '/streams/$streamId'
      path: '/$streamId'
      fullPath: '/streams/$streamId'
      preLoaderRoute: typeof StreamsStreamIdRouteImport
      parentRoute: typeof StreamsRoute
    }
    '/api/sse/$id': {
      id: '/api/sse/$id'
      path: '/api/sse/$id'
      fullPath: '/api/sse/$id'
      preLoaderRoute: typeof ApiSseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StreamsRouteChildren {
  StreamsStreamIdRoute: typeof StreamsStreamIdRoute
}

const StreamsRouteChildren: StreamsRouteChildren = {
  StreamsStreamIdRoute: StreamsStreamIdRoute,
}

const StreamsRouteWithChildren =
  StreamsRoute._addFileChildren(StreamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StreamsRoute: StreamsRouteWithChildren,
  ApiSseIdRoute: ApiSseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
