/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as InspectRouteImport } from './routes/inspect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InspectStreamIdRouteImport } from './routes/inspect.$streamId'
import { Route as ApiSseIdRouteImport } from './routes/api/sse.$id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectRoute = InspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectStreamIdRoute = InspectStreamIdRouteImport.update({
  id: '/$streamId',
  path: '/$streamId',
  getParentRoute: () => InspectRoute,
} as any)
const ApiSseIdRoute = ApiSseIdRouteImport.update({
  id: '/api/sse/$id',
  path: '/api/sse/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inspect': typeof InspectRouteWithChildren
  '/test': typeof TestRoute
  '/inspect/$streamId': typeof InspectStreamIdRoute
  '/api/sse/$id': typeof ApiSseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inspect': typeof InspectRouteWithChildren
  '/test': typeof TestRoute
  '/inspect/$streamId': typeof InspectStreamIdRoute
  '/api/sse/$id': typeof ApiSseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inspect': typeof InspectRouteWithChildren
  '/test': typeof TestRoute
  '/inspect/$streamId': typeof InspectStreamIdRoute
  '/api/sse/$id': typeof ApiSseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/inspect' | '/test' | '/inspect/$streamId' | '/api/sse/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/inspect' | '/test' | '/inspect/$streamId' | '/api/sse/$id'
  id:
    | '__root__'
    | '/'
    | '/inspect'
    | '/test'
    | '/inspect/$streamId'
    | '/api/sse/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InspectRoute: typeof InspectRouteWithChildren
  TestRoute: typeof TestRoute
  ApiSseIdRoute: typeof ApiSseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect': {
      id: '/inspect'
      path: '/inspect'
      fullPath: '/inspect'
      preLoaderRoute: typeof InspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect/$streamId': {
      id: '/inspect/$streamId'
      path: '/$streamId'
      fullPath: '/inspect/$streamId'
      preLoaderRoute: typeof InspectStreamIdRouteImport
      parentRoute: typeof InspectRoute
    }
    '/api/sse/$id': {
      id: '/api/sse/$id'
      path: '/api/sse/$id'
      fullPath: '/api/sse/$id'
      preLoaderRoute: typeof ApiSseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InspectRouteChildren {
  InspectStreamIdRoute: typeof InspectStreamIdRoute
}

const InspectRouteChildren: InspectRouteChildren = {
  InspectStreamIdRoute: InspectStreamIdRoute,
}

const InspectRouteWithChildren =
  InspectRoute._addFileChildren(InspectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InspectRoute: InspectRouteWithChildren,
  TestRoute: TestRoute,
  ApiSseIdRoute: ApiSseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
