/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdSessionsRouteImport } from './routes/projects.$projectId.sessions'
import { Route as ProjectsProjectIdPublishRouteImport } from './routes/projects.$projectId.publish'
import { Route as ProjectsProjectIdSessionsIdRouteImport } from './routes/projects.$projectId.sessions.$id'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdSessionsRoute =
  ProjectsProjectIdSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdPublishRoute =
  ProjectsProjectIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdSessionsIdRoute =
  ProjectsProjectIdSessionsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProjectsProjectIdSessionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/publish': typeof ProjectsProjectIdPublishRoute
  '/projects/$projectId/sessions': typeof ProjectsProjectIdSessionsRouteWithChildren
  '/projects/$projectId/sessions/$id': typeof ProjectsProjectIdSessionsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/publish': typeof ProjectsProjectIdPublishRoute
  '/projects/$projectId/sessions': typeof ProjectsProjectIdSessionsRouteWithChildren
  '/projects/$projectId/sessions/$id': typeof ProjectsProjectIdSessionsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/projects/$projectId/publish': typeof ProjectsProjectIdPublishRoute
  '/projects/$projectId/sessions': typeof ProjectsProjectIdSessionsRouteWithChildren
  '/projects/$projectId/sessions/$id': typeof ProjectsProjectIdSessionsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/publish'
    | '/projects/$projectId/sessions'
    | '/projects/$projectId/sessions/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/publish'
    | '/projects/$projectId/sessions'
    | '/projects/$projectId/sessions/$id'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/projects/$projectId'
    | '/projects/$projectId/publish'
    | '/projects/$projectId/sessions'
    | '/projects/$projectId/sessions/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$projectId/sessions': {
      id: '/projects/$projectId/sessions'
      path: '/sessions'
      fullPath: '/projects/$projectId/sessions'
      preLoaderRoute: typeof ProjectsProjectIdSessionsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/publish': {
      id: '/projects/$projectId/publish'
      path: '/publish'
      fullPath: '/projects/$projectId/publish'
      preLoaderRoute: typeof ProjectsProjectIdPublishRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/sessions/$id': {
      id: '/projects/$projectId/sessions/$id'
      path: '/$id'
      fullPath: '/projects/$projectId/sessions/$id'
      preLoaderRoute: typeof ProjectsProjectIdSessionsIdRouteImport
      parentRoute: typeof ProjectsProjectIdSessionsRoute
    }
  }
}

interface ProjectsProjectIdSessionsRouteChildren {
  ProjectsProjectIdSessionsIdRoute: typeof ProjectsProjectIdSessionsIdRoute
}

const ProjectsProjectIdSessionsRouteChildren: ProjectsProjectIdSessionsRouteChildren =
  {
    ProjectsProjectIdSessionsIdRoute: ProjectsProjectIdSessionsIdRoute,
  }

const ProjectsProjectIdSessionsRouteWithChildren =
  ProjectsProjectIdSessionsRoute._addFileChildren(
    ProjectsProjectIdSessionsRouteChildren,
  )

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdPublishRoute: typeof ProjectsProjectIdPublishRoute
  ProjectsProjectIdSessionsRoute: typeof ProjectsProjectIdSessionsRouteWithChildren
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdPublishRoute: ProjectsProjectIdPublishRoute,
  ProjectsProjectIdSessionsRoute: ProjectsProjectIdSessionsRouteWithChildren,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
