/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleProjectStreamIdRouteImport } from './routes/console.$project.stream.$id'
import { Route as ConsoleProjectSessionIdRouteImport } from './routes/console.$project.session.$id'
import { Route as ApiSseProjectIdRouteImport } from './routes/api/sse.$project.$id'

const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleProjectStreamIdRoute = ConsoleProjectStreamIdRouteImport.update({
  id: '/$project/stream/$id',
  path: '/$project/stream/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleProjectSessionIdRoute = ConsoleProjectSessionIdRouteImport.update({
  id: '/$project/session/$id',
  path: '/$project/session/$id',
  getParentRoute: () => ConsoleRoute,
} as any)
const ApiSseProjectIdRoute = ApiSseProjectIdRouteImport.update({
  id: '/api/sse/$project/$id',
  path: '/api/sse/$project/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/api/sse/$project/$id': typeof ApiSseProjectIdRoute
  '/console/$project/session/$id': typeof ConsoleProjectSessionIdRoute
  '/console/$project/stream/$id': typeof ConsoleProjectStreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/api/sse/$project/$id': typeof ApiSseProjectIdRoute
  '/console/$project/session/$id': typeof ConsoleProjectSessionIdRoute
  '/console/$project/stream/$id': typeof ConsoleProjectStreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/api/sse/$project/$id': typeof ApiSseProjectIdRoute
  '/console/$project/session/$id': typeof ConsoleProjectSessionIdRoute
  '/console/$project/stream/$id': typeof ConsoleProjectStreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/api/sse/$project/$id'
    | '/console/$project/session/$id'
    | '/console/$project/stream/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console'
    | '/api/sse/$project/$id'
    | '/console/$project/session/$id'
    | '/console/$project/stream/$id'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/api/sse/$project/$id'
    | '/console/$project/session/$id'
    | '/console/$project/stream/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  ApiSseProjectIdRoute: typeof ApiSseProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/$project/stream/$id': {
      id: '/console/$project/stream/$id'
      path: '/$project/stream/$id'
      fullPath: '/console/$project/stream/$id'
      preLoaderRoute: typeof ConsoleProjectStreamIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/$project/session/$id': {
      id: '/console/$project/session/$id'
      path: '/$project/session/$id'
      fullPath: '/console/$project/session/$id'
      preLoaderRoute: typeof ConsoleProjectSessionIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/api/sse/$project/$id': {
      id: '/api/sse/$project/$id'
      path: '/api/sse/$project/$id'
      fullPath: '/api/sse/$project/$id'
      preLoaderRoute: typeof ApiSseProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleProjectSessionIdRoute: typeof ConsoleProjectSessionIdRoute
  ConsoleProjectStreamIdRoute: typeof ConsoleProjectStreamIdRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleProjectSessionIdRoute: ConsoleProjectSessionIdRoute,
  ConsoleProjectStreamIdRoute: ConsoleProjectStreamIdRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  ApiSseProjectIdRoute: ApiSseProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
